# Generated by Django 4.2.8 on 2023-12-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Order', '0002_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
