# Generated by Django 4.2.8 on 2023-12-10 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Order', '0003_order_coupon_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon_code',
        ),
    ]
