# Generated by Django 4.2.8 on 2023-12-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Order', '0004_remove_order_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
