# Generated by Django 4.2.8 on 2023-12-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Seller', 'Seller')], default='Normal', max_length=10),
            preserve_default=False,
        ),
    ]
